### ISSUE TITLE
Thank you very much for your project, which solved my problem

### ISSUE THREAD

**Issue by gitxinyi** [mirusu400/Pinterest-infinite-crawler#1]
I made some changes to the code for my business
python3  main.py 1 dog 123

It is recommended to add automatic creation of download directories
![image](https://user-images.githubusercontent.com/28300658/131322338-e104a5c5-1f8a-44ef-b935-b51afb2f0f92.png)

**Comment by mirusu400** [comment]
It seems better to use `sys.argv` instead `input`, but for now, I just use input for non-cli users. I'll add the both ways to download(eg. argument override)

Anyway, checking / makeing directory are so nice, I'll add these later. Thanks!

**Comment by gitxinyi** [comment]
that's great, Because I need to download pictures from different channels, I need to use the program to call, so it is more convenient to use the command。

**Comment by mirusu400** [comment]
I add argparse for general users, now you can use with some arguments. See README for detailed documentation.

```
usage: main.py [-h] [-e EMAIL] [-p PASSWORD] [-d DIRECTORY] [-l LINK] [-g PAGE]

optional arguments:
  -h, --help                            show this help message and exit
  -e EMAIL, --email EMAIL               Your Pinterest account email
  -p PASSWORD, --password PASSWORD      Your Pinterest account password
  -d DIRECTORY, --directory DIRECTORY   Directory you want to download
  -l LINK, --link LINK                  Link of Pinterest which you want to scrape
  -g PAGE, --page PAGE                  Number of pages which you want to scrape

example
main.py -e mirusu400@naver.com -p [your_password] -d download_image -l https://pinterest.com/ -g 10
```
