### ISSUE TITLE
Is your crawl normal?

### ISSUE THREAD

**Issue by gitxinyi** [mirusu400/Pinterest-infinite-crawler#2]
Is your crawl normal? It seems to be stuck in the log-in. It may be restricted by anti-crawler

![image](https://user-images.githubusercontent.com/28300658/131978670-879671aa-70b0-4e6b-8e1f-1ab49427c819.png)

**Comment by mirusu400** [comment]
Yes, It seems that if you try to login 10 times in a row(Even if succesfully login), Pinterest blocks your account temporary and you can't login. I'll make a batch downloader (multiple page in a row) If I have much time.

**Comment by gitxinyi** [comment]
Thank you for your efforts, it seems that Pinterest's anti-crawler is quite strict, I found many on Github, yours is relatively easy to use, others have not been maintained for a long time

**Comment by gitxinyi** [comment]
After checking some information, I found that the cookie information after login can be stored in a file, and then login after the cookie is invalid

**Comment by gitxinyi** [comment]
After checking some information, I found that the cookie information after login can be stored in a file, and then login after the cookie is invalid

**Comment by mirusu400** [comment]
If you in hurry, you can simply edit `main.py` and add call some methods if you want to batch-download.
```diff
    print("Open selenium...")
++    # at this time, Pinterest tries to login
    p = Pinterest(email, password)

    print("Download Image")
++    # call more methods..
    p.crawl(pages, "link1", directory)
++    p.crawl(pages, "link2", directory)
++    p.crawl(pages, "link3", directory)
...
```

**Comment by gitxinyi** [comment]
I have adjusted the code. My requirement is to search images by keyword and download hundreds of images at a time, mainly to solve the problem of frequent login.

**Comment by mirusu400** [comment]
Then we need to fix core methods to call pages asynchronously (ex. open multiple ages in a row and scroll down asynchronously) but It's hard work in python.. I'll update it later

**Comment by gitxinyi** [comment]
Tweaked ppinterest. Py file, referenced cookie, late call, no longer logged in.My development environment is Linux Ubuntu 18.04
  
from selenium import webdriver
from bs4 import BeautifulSoup
from imagehelper import *
from time import sleep
from sys import exit
import asyncio ,pickle
class Pinterest():
    def __init__(self, login, pw):
        self.piclist = []
        options = webdriver.ChromeOptions()
        options.add_argument('headless')
        options.add_argument('window-size=1920x1080')
        options.add_argument("disable-gpu")
        options.add_argument("--no-sandbox")
        options.add_argument("--disable-dev-shm-usage")

        self.driver = webdriver.Chrome('./bin/chromedriver', chrome_options=options)
        self.driver.get("https://pinterest.com/login")

        browser_cookies = self.driver.get_cookies()
        noLogin_cookies = {}
        for item in browser_cookies:
            noLogin_cookies[item['name']] = item['value']
        print('no login cookie==========')
        print(noLogin_cookies)

        try :
            print('Assemble the cookie =====')
            cookie_pin = pickle.load(open('cookie.pin', 'rb'))
            for cookie in cookie_pin:
                self.driver.add_cookie({
                    "domain": ".pinterest.com",
                    "name": cookie,
                    "value": cookie_pin[cookie],
                    "path": '/'
                    # "expires": None
                })
        except:
            print('logging =====')
            self.driver.get("https://pinterest.com/login")
            emailelem = self.driver.find_element_by_id("email")
            passelem = self.driver.find_element_by_id("password")
            emailelem.send_keys(login)
            passelem.send_keys(pw)
            sleep(1)
            self.driver.find_element_by_xpath("//button[@type='submit']").click()
            sleep(1)

        self.driver.get("https://pinterest.com/login")
        browser_cookies = self.driver.get_cookies()
        cookies = {}
        for item in browser_cookies:
            cookies[item['name']] = item['value']
            outputPath = open('cookie.pin', 'wb')
            pickle.dump(cookies, outputPath)

        print('login cookie==========')
        print(cookies)


    def crawl(self, n=-1, url="https://pinterest.com/", dir="./download"):
        global loop
        fail_image = 0
        if n == -1:
            n = 999999999
        loop = asyncio.get_event_loop()
        
        self.driver.get(url)
        self.driver.implicitly_wait(3)
        for i in range(n):
            timeout = 0
            download_pic_count = len(self.piclist)
            print(f"Scroll down {i} Page, downloaded {download_pic_count} images.")
            height = self.driver.execute_script("return document.body.scrollHeight")
            while True:
                self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
                sleep(2)
                now_height = self.driver.execute_script("return document.body.scrollHeight")

                # If height changed
                if now_height != height:
                    self.download_image(dir)
                    break
                else:
                    timeout += 1
                    if timeout >= 10:
                        print("It seems we find the end of current page, stop crawling.")
                        print(f"Totally scroll down {i} page, download {download_pic_count} images.")
                        exit()
            sleep(2)
        loop.close
    
    def getdriver(self):
        return self.driver

    def download_image(self, dir="./download"):
        page_pic_list=[]
        req = self.driver.page_source
        soup = BeautifulSoup(req, 'html.parser')
        pics = soup.find_all("img")
        if pics is None:
            return 0
        for pic in pics:
            src = pic.get("src")
            
            # Profile image, skip
            if "75x75_RS" in src:
                continue

            if src not in self.piclist:
                self.piclist.append(src)
                page_pic_list.append(src)
        
        fail_image = sum(loop.run_until_complete(download_image_host(page_pic_list,dir)))
        return fail_image
 
The test is normal, and no account or password is used to log in
![image](https://user-images.githubusercontent.com/28300658/132493820-ca59f01a-5f2e-41a9-9147-29cbe5383103.png)

**Comment by mirusu400** [comment]
Ok, I add `batch download` for my program, so you should easily download by only writing simple json file.
> main.py -b

Also, I add your cookie method, it automatically save your cookies and trying to login with these cookies.
But It doesn't work for my environment, unfortunately. (Maybe it works for your environment)
