### ISSUE TITLE
이미지 사이즈를 설정할 수 있는 방법은 없을까요?

### ISSUE THREAD

**Issue by offsong** [mirusu400/Pinterest-infinite-crawler#4]
예를 들어 다른사람의 모여져있는 핀을 크롤링 할때 내가 원하는 특정사이즈 이상의 이미지만 가져올 수 있게끔
처리할 수 있는 방법이 있는지 궁금합니다!

**Comment by mirusu400** [comment]
본 프로그램의 목적이 이미지 크롤링만 목적이고, 후처리에 대해서는 구현할 예정이 딱히 없습니다.

ChatGPT 등을 이용하시면 쉽게 구현하실 수 있을 것 같아요
